use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :adpq, AdpqWeb.Endpoint,
  http: [port: {:system, "PHOENIX_PORT"}],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:adpq, :vsn)  

# Do not print debug messages in production
config :logger, level: :info


config :adpq, Adpq.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("POSTGRES_USER"),
  password: System.get_env("POSTGRES_PASSWORD"),
  database: System.get_env("POSTGRES_DATABASE"),
  socket: System.get_env("POSTGRES_SOCKET_PATH"),
  timeout: 7200_000,
  pool_size: 3   

config :adpq, AdpqWeb.Endpoint,
  secret_key_base: "Y8xMqKI4RKA19P9K3CG4AnaYtf1eu8GqTmZyxMlluiyV12j/3Nki+WC83S9e3XVe"

# Honeybadger
#config :honeybadger, environment_name: :production

config :adpq, swagger_host: "adpq.labzero.com"