use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :adpq, Adpq.Endpoint,
  http: [port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :adpq, Adpq.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "adpq_production",
  password: System.get_env("RDS_PASSWORD"),
  database: "adpq_production",
  hostname: "adpq-production.cuhwr9egpxgb.us-west-1.rds.amazonaws.com",
  pool_size: 10

config :adpq, Adpq.Endpoint,
  secret_key_base: "Y8xMqKI4RKA19P9K3CG4AnaYtf1eu8GqTmZyxMlluiyV12j/3Nki+WC83S9e3XVe"
